# 任务的名称
name: CI
# 触发任务执行的事件
on:
  - push
  - pull_request
# 定义需要执行的任务
jobs:
  # 任务 <job_id>
  test:
    # 任务名称 jobs.<job_id>.name 将在 Github UI中展示
    name: Node.js ${{ matrix.node-version }}
    # 任务的执行容器
    runs-on: ubuntu-latest
    # 任务的策略矩阵
    strategy:
      # 表示任务执行失败之后,是否终止其他正在执行的任务
      fail-fast: false
      # 这里表示任务将在3个不同的node版本下执行
      # 也就是会执行3个不同的任务
      matrix:
        node-version:
          - 16
          - 14
          - 12
    # 定义任务的步骤
    steps:
      # 拉取代码
      - uses: actions/checkout@v2
      # 初始化node环境
      - uses: actions/setup-node@v2
        # 提供给actions/setup-node@v2的环境变量
        with:
          node-version: ${{ matrix.node-version }}
      # 执行的shell命令
      - run: npm install
      - run: npm test
